feat: web call sidecar http (#382)
* Add <title> to index.html

* Remove call to load references for a new sample project

* for web, send sidecar requests to the backend HTTP server (via proxy)

* reimplement http.py function names (for handlers) and "fix" imports

Note: I've had to change this bc I was getting an error like:

```
    response = sidecar.ingest.get_statuses()
               ^^^^^^^^^^^^^^
AttributeError: module 'sidecar' has no attribute 'ingest'
```

* Add utility scripts and instructions for the web.

* Remove unused import

* Fix PR comments

- Update HTTP api interface
- Update format save rules for python